### ISSUE TITLE
README is lacking information

### ISSUE THREAD

**Issue by mkappas** [janablechschmidt/MetaRange.jl#10]
Hi. Today, I had a look at the repository and I feel that there is a lot of room for improvement regarding the documentation. For example, as an outsider, I have no idea what I need to install, how to run the program, what to expect to get back, whether I need any input or configuration files (there are only some incomplete instructions in the `docs` directory).

The following is just a suggestion of what sections we could add to the `README.md` but of course we can deviate from this if it doesn't feel right for this project.

I suggest that we do it do it via a typical git workflow (branch out of `main` and then create a Pull Request) and when ready you can add me as a reviewer. Adding the text "This PR closes #NUMBER" in the description of the PR, where NUMBER is the id of this issue will close the Issue automatically upon merging ([link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)).

# MetaRange

[Simple overview / summary]

MetaRange is a process-based mechanistic species distribution model, that explicitly includes stochastic as well as metabolic processes. It is intended to be used as a general mechanistic distribution model for theoretical questions as well as a predictive tool to model future species distributions based on empirical data.

## Introduction / About / Description

[A more in-depth description of the model/code but still a few paragraphs, not a 2000 words essay.]

## Installation / Setup

[Do we need a particular Julia version? Any packages? How do we install those?]

## Launch / Usage

[How to run the program. Do we need any input or configurations files and how do we get/create them? What is the expected output? A sample execution with any input arguments and the output might also be useful.]

## Tests

[How to run the tests, if any.]

## License

This project is licensed under the terms of the **MIT** license. See `LICENSE` for more information.

## Acknowledgments

This module is an adaptation of the [metaRange](https://srfall.github.io/metaRange) model written in R.

**Comment by rroelz** [comment]
Definitely warranted, I've barely started on working on the documentation. To the Launch/Usage part, that's actually one of our big questions how to best solve this and make it usable for someone that doesn't have the data or the files we use, as there's a bunch.  
I don't know how good of an idea it is to have them here, as this is really more supposed to be a Package that you install with the package manager and don't need to know where it is and let Julia handle it. Maybe using `Scratch.jl` or have a function that wites out a bunch of configs? But That part is definitely one that needs more figuring out.
