### ISSUE TITLE
example input for users

### ISSUE THREAD

**Issue by janablechschmidt** [janablechschmidt/MetaRange.jl#19]
I want to add an option in the default_run_data() function that creates a directory with the simulation input. This way, new users can inspect the folder and file structure that is required to successfully run the model and play around with it.

**Comment by rroelz** [comment]
Maybe we could have some small examples in a `MetaRange/examples` folder? Probably not all of bavaria but smaller scale ones. Compare for example [Agents.jl](https://github.com/JuliaDynamics/Agents.jl/tree/main/examples)

**Comment by rroelz** [comment]
#78e7bfc should fix this

**Comment by rroelz** [comment]
solved through other means
