### ISSUE TITLE
Allow read_input() to read either a path to a .csv or a path to the folder

### ISSUE THREAD

**Issue by rroelz** [janablechschmidt/MetaRange.jl#27]
When passing `read_input()` the complete path to the `config.csv` file the function `read_sp()`(read_input.jl:27) directly extends it to `path/to/config.csv/config.csv`. I think it would make more sense to allow pointing to either. Though I could see how that leads to a bit more work.

**Comment by mkappas** [comment]
We've discussed this today with @janablechschmidt and we think that we might need -at least- two more parameters in the configuration file. Those will be `species_dir` and `environment_dir` and they will point to the corresponding directories, either via absolute paths or relative from the directory containing the configuration file. This means that the user can name the configuration file as they want and they won't have to follow the current structure. It also means that it might be best to only allow the user to pass a path to the configuration file itself and drop completely support for the current structure, where the user specifies only the path where the aforementioned directories and the config file are expected to be found.

**Note:** I've noticed that there is a third directory, named `config_dir`. What is this for? Currently it is hardcoded to `config_path = "./TESTRUN"`.
**Note 2:** I've also noticed that there are two more files that we specify in the configuration file, `temperature` and `precipitation` and those are expected to be found in the environment directory, but we pass only the name of the files (so it's relative from the environment dir). We should probably rethink how we want the user to specify those as well.

Let me know what you think.
