### ISSUE TITLE
Warnings in documentation CI became errors after merging

### ISSUE THREAD

**Issue by mkappas** [janablechschmidt/MetaRange.jl#44]
We were getting some warnings from the Documentation CI (example [here](https://github.com/janablechschmidt/MetaRange.jl/actions/runs/6196651418)) which became errors after merging the last two pull requests in main (for example [here](https://github.com/janablechschmidt/MetaRange.jl/actions/runs/6198812863)). I'm not yet sure why this has happened.

**Comment by janablechschmidt** [comment]
I think we will have to replace "@ref" with the actual reference that we want to link

**Comment by rroelz** [comment]
The change in Documenter.jl on update to Version [v1.0.0](https://github.com/JuliaDocs/Documenter.jl/blob/v1.0.1/CHANGELOG.md#version-v100---2023-09-15) changed from default behavior of warnings to Errors. I'll try and solve them properly though so there's no warnings.

**Comment by mkappas** [comment]
> The change in Documenter.jl on update to Version [v1.0.0](https://github.com/JuliaDocs/Documenter.jl/blob/v1.0.1/CHANGELOG.md#version-v100---2023-09-15) changed from default behavior of warnings to Errors. I'll try and solve them properly though so there's no warnings.

Good catch! A quick and dirty solution is to set `warnonly = true` but then we might forget to fix the warnings, so it's probably better to just identify and fix them.

**Comment by rroelz** [comment]
yep, that was my train of thought as well
