### ISSUE TITLE
abundance zero on the left border

### ISSUE THREAD

**Issue by rroelz** [janablechschmidt/MetaRange.jl#54]
When comparing visuals of the simulations there seems to consistently be an abundance of 0 in the leftmost patches.  
Compare the static abundance gif  
![static_abundance](https://github.com/janablechschmidt/MetaRange.jl/assets/77731816/dc87b052-2dda-4262-b3a6-194fea5769e9)
Or the bavaria one where it's only visible in the very very left point  
![Abundances](https://github.com/janablechschmidt/MetaRange.jl/assets/77731816/9f1803af-78df-4800-8b73-e30eabc36d8e)
This is probably not expected behaviour? If not probably have to figure out what's going on there.

**Comment by janablechschmidt** [comment]
could be an edge effect - I've been meaning to re-write the dispersal function so that we have reflecting edges instead, just haven't gotten to it yet

**Comment by rroelz** [comment]
I'm just surprised because it's never the case at any of the other borders. It's always the left one.

**Comment by janablechschmidt** [comment]
yeah that's weird. I'll have a look

**Comment by rroelz** [comment]
been checking with 
```julia
[sum(skipmissing(SD.species[1].abundances[:,1,x])) for x in 1:100]
```
over all timesteps and it's always nonzero in the first step and then after it goes down to 0 and stays there

**Comment by rroelz** [comment]
Problem seems to be `HabitatMortality` I added tests in commit #8448d3063e7a28cb93be568cbe520f91d01be78b and they fail with weird behaviour
