### ISSUE TITLE
make sure Survive!() works

### ISSUE THREAD

**Issue by rroelz** [janablechschmidt/MetaRange.jl#61]
Function survive at in [eco_loop_functions.jl](https://github.com/janablechschmidt/MetaRange.jl/blob/d77ec0ea3a864e25f92ddacd6dd301c2a3ede363/src/eco_loop_functions.jl#L416) has one of the faulty `hcat()` constructions that also appeared to be at fault in #54. We should check whether it works or breaks something and fix it if it does

**Comment by janablechschmidt** [comment]
I checked - this works as intended!
