### ISSUE TITLE
Weird abundance spikes

### ISSUE THREAD

**Issue by rroelz** [janablechschmidt/MetaRange.jl#71]
When simulation sometimes the abundance spikes very high or very low in just one patch. Conditions aren't quite clear but happens often enough that it's quite noticeable. This is from `examples/static` run with julia 1.9.3 on ubuntu
Timestep 2: 
![image](https://github.com/janablechschmidt/MetaRange.jl/assets/77731816/67a986fe-0ae8-463a-8ed5-2079e7acd704)

Timestep 3:
![image](https://github.com/janablechschmidt/MetaRange.jl/assets/77731816/85c9bd0d-eae7-4217-ad4f-b544880a98d0)

**Comment by rroelz** [comment]
It's not noticeable enough overall though

![image](https://github.com/janablechschmidt/MetaRange.jl/assets/77731816/9829abc8-afd0-4e08-9b88-897694d8ed98)

**Comment by janablechschmidt** [comment]
works as intended
