### ISSUE TITLE
function to save output

### ISSUE THREAD

**Issue by janablechschmidt** [janablechschmidt/MetaRange.jl#78]
We need a function that saves the simulation output.
The function should create a folder for each saved parameter and save the output as a CSV file for each timestep.
Saved parameters include:
- Abundance
- Habitat suitability
- Reproduction rate
- Mortality rate
- Carrying capacity

Ideally, we provide the user options to just save selected parameters, but for now let's just get this function started.

**Comment by rroelz** [comment]
I am currently wondering. Would it make more sense to combine all in a table rather than having to write a file for each timestep?

**Comment by rroelz** [comment]
Pro -> only one or fewer files to process
Con -> losing the matrix aspect in the file. This isn't a strong suit of CSVs though anyway

**Comment by rroelz** [comment]
It's probably best to first solve other problems with the output directories like #77 to have a stable output folder into which it can be directly written.
